name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev
      - name: Build (Makefile project)
        working-directory: Malware_Analyzer
        run: make -j
      - name: Smoke test (static analyze /bin/ls)
        working-directory: Malware_Analyzer
        run: ./malx static /bin/ls --json --pretty
